# Generated by Django 5.2.3 on 2025-06-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0002_quiz_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_5',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizcore.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizcore.question')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_for', to='quizcore.answer'),
        ),
    ]
