# Generated by Django 5.2.3 on 2025-06-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0003_remove_question_answer_1_remove_question_answer_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_for', to='quizcore.answer'),
        ),
    ]
